### PR TITLE
launch coveralls on unsupported CI-backends

### PR DESCRIPTION
**Pull request by kirillseva**
by specifying `repo-token`

### CODE REVIEW

**Comment by kirillseva** [comment]
I'll resolve lintr issue after Travis build finishes

**Comment by kirillseva** [comment]
I see :)

**Comment by jimhester** [comment]
Sorry about the redundant lintr-bot comment, need to fix that bug.

**Comment by kirillseva** [comment]
Yep. And there will be one more. BTW lintr-bot is great, I should set it up for my packages as well

**Comment by jimhester** [comment]
If you are already using testthat in your package you can just add 

```r
if (requireNamespace("lintr", quietly = TRUE)) {
  context("lints")
  test_that("Package Style", {
    expect_lint_free()
  })
}
```

To your tests and it will fail when there are lints.

If not just put the following in your `travis.yaml`
```r
after_success:
  Rscript -e 'lintr::lint_package()'
```

Currently lintr-bot only works with builds on travis, but that will probably change in the future.

Probably the hardest thing to do is make sure your build does not have a lints to begin with :smile:

**Comment by jimhester** [comment]
Also btw this looks good, thank you for writing it.  I will merge it once the tests pass.

**Comment by kirillseva** [comment]
Green! :neckbeard:

**Comment by kirillseva** [comment]
Hmm, this definitely works, as in new coveralls builds are being created... However, the coverage is 0%.
```r
$source_files[[27]]$coverage
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  0  0 NA  0  0  0  0  0
[26] NA NA  0 NA NA  0  0  0 NA  0 NA NA  0  0  0 NA  0 NA  0  0 NA NA NA NA NA
[51] NA  0  0  0  0  0  0  0  0  0  0  0  0
```
I'm doing
```r
devtools::install()
devtools::test()
library(covr);
coveralls(repo_token=Sys.getenv("COVERALLS_SECRET"))
```

Any obvious explanation off the top of your head @jimhester ?

**Comment by kirillseva** [comment]
Ok, that's good to merge. The problem was that my tests were in `inst/tests` instead of 'tests/testthat'

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
