### PR TITLE
Summary functions

### PR DESCRIPTION
**Pull request by rmflight**
Add two new functions useful for a package developer / maintainer on their own machine: 

* percent_coverage: gives how much test coverage there is by looking at how many zero values there is in the package_coverage output
* zero_coverage: returns just the zero locations, and the really relevant pieces of the package_coverage output to help the developer navigate to the file locations

Unfortunately, I can't find a way to test these on covr itself, I get a recursion issue if I do that.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks for working on this!

You can add tests for your functions by running package_coverage on one of the test packages in `tests/testthat/` (note that test are run from the `tests/testthat` directory)

e.g.
```r
context("summary_functions")
cov <- package_coverage('TestS4')
test_that("percent_coverage returns correct output", {
expect_equals(percent_coverage(cov), .543)
})
```

Also an admittedly silly thing could you rename `n_lines` and `n_not_zero` to `num_lines` and `num_not_zero`.

Thanks again!

**Comment by rmflight** [comment]
Do these work for you?

**Comment by jimhester** [comment]
Yep that works.  I should probably make a project that has intermediate coverage so the tests are less trivial but we will leave that for another day.

**Comment by rmflight** [comment]
Yes, ideally we would have that. I can probably create that package for testing the first of next week.

**Comment by rmflight** [comment]
OK, so once I thought about it, that took about 10 minutes to do. 

This pull request now:

closes #13 
closes #14 
closes #17

**Comment by jimhester** [comment]
Awesome, thanks for your work on this!  Looks great.

One thing that might be useful for these summary functions is to stratify the results by file (should be easy) or even by enclosing function (pretty challenging with the current covr implementation)

If you want to do either of the above in this pull I can wait to merge it or I can merge it as-is now and I can add the functionality later (or you can open a new pull request).

**Comment by rmflight** [comment]
This might be an interesting option to add later, but I think I would merge as is for now.

My reasoning is that the `percent_coverage` gives a good overview of how the package is as a whole, and doesn't really need broken down by file. The `zero_coverage` has the `filename` column in the results, and this points a developer directly to the file and line that is not currently being tested. I was going to split out the results by file until I observed that the `coverage` data.frame is sorted by filename and line. This also goes for the enclosing function, because a developer would have the source right in front of them.

I guess one option would be to be able to specify which file one wants the coverage for, which in that case the easiest thing would be to break it up by file initially. If you want, open an issue and assign me to it?

**Comment by jimhester** [comment]
Fair points, thanks for the contribution!

**Comment by jimhester** [comment]
Also FYI if you put the 
```
closes #13 
closes #14 
closes #15 
closes #16 
closes #17
```
In your git commit message github will automatically close the issues when I merge the pull.

**Pull request merged**
