### PR TITLE
AppVeyor expects its service name all lowercase

### PR DESCRIPTION
**Pull request by wamserma**
see https://codecov.io/bash VERSION="e7c0c15"

### CODE REVIEW

**Comment by wamserma** [comment]
Sorry, i forgot to to edit the String at https://github.com/jimhester/covr/blob/master/tests/testthat/test-codecov.R#L329
Also, Steve from Codecov was looking into allowing both, "appveyor" and "AppVeyor". I asked him to report back here if and when this has reached production.

**Comment by jimhester** [comment]
@wamserma Please commit the additional change and push to the same branch you opened this PR from, it will update the PR with the changes.

**Comment by wamserma** [comment]
@jimhester Done. The build fail on Travis seems unrelated.

**Comment by jimhester** [comment]
Great, thanks!

**Pull request merged**
