### PR TITLE
Now coveralls(..., quiet=TRUE) print():s coverage.

### PR DESCRIPTION
**Pull request by HenrikBengtsson**
I have had issues with Coveralls not listing my jobs, although they are created and uploaded.  This currently only occurs for one of my many repository.

* R.oo list of jobs: https://coveralls.io/r/HenrikBengtsson/R.oo (~~completely empty~~)
* R.oo coverage job: https://coveralls.io/jobs/4187059

Searching the web, there are several reports on this (e.g. https://github.com/lemurheavy/coveralls-public/issues/281) and yet have to find an answer/solution to the problem. 

So, in the efforts on troubleshooting this one, I wanted to see what coverage 'covr' uploads from Travis CI, which is why I added support for `covr::coveralls(quiet=TRUE)`, e.g. see end of https://travis-ci.org/HenrikBengtsson/R.oo/builds/48542721.

I kept it backward compatibility, hence the default `quiet=FALSE`.

## UPDATE
Just adding these notes here in case someone else have similar problems and discovers this post.  I first discovered that Coveralls listed several files to have "no data" within each jobs.  Then manually going through those, I discovered that the files for which data was missing where all alphabetically at the beginning, and then "all of a sudden" the remaining files had data. I also discovered that the last file for which data did not exist, linked to a broken page on Coveralls, i.e. the link for `R/equals.default.R` listed by [R.oo job 38.1](https://coveralls.io/jobs/4188393) is [broken](https://coveralls.io/files/444656217).  I added an explicit test for function, but that made no difference - the link to that file is still [broken](https://coveralls.io/files/444765102) in [R.oo job 39.1](https://coveralls.io/jobs/4189460).  Interestingly, the covr output (using `quiet=FALSE`) also show that that file has [zero coverage](https://travis-ci.org/HenrikBengtsson/R.oo/builds/48563210), which it shouldn't have.

Now, here's the really interesting part.  In the next iteration/commit/push, I added test cases for another file, R/ASCII.R, which is ahead in alphabetic sense.  Nothing else was done, cf. R.oo Commit [81b1232](https://github.com/HenrikBengtsson/R.oo/commit/81b12322120017859cefe223f4526e51a83bc0f9).  That file now reports 100% coverage, but more importantly that triggered covr to all of a sudden also report [100%](https://travis-ci.org/HenrikBengtsson/R.oo/builds/48564405) for `R/equals.default.R`.

From this I am starting to believe this issue has to do with 'covr' et al. rather than Coveralls.  It's seems that the internal coverage data somehow can become broken which is revealed both by `print()` but also what is uploaded to Coveralls.

Phew.

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Several of the links under 'Update' section above where incorrect. Fixed.

**Comment by HenrikBengtsson** [comment]
Now I understand you comment on using `httr::stop_for_status(result)`; I forgot that I threw in that:
```r
if (isTRUE(content$error)) {
   stop("Failed to upload coverage data. Reply by Coveralls: ", content$message)
}
```
test.

**Comment by jimhester** [comment]
Thanks again for this pull request, you can now use `quiet = FALSE` to print the coverage results before uploading them, or use a pre-existing coverage result using the `coverage` parameter.

**Comment by HenrikBengtsson** [comment]
Great. Thxs

**Pull request merged**
