### PR TITLE
Do not delete .def source files

### PR DESCRIPTION
**Pull request by jeroenooms**
Fixes https://github.com/jimhester/covr/issues/167.

### CODE REVIEW

**Comment by jimhester** [comment]
Yeah that seems correct, we should not be deleting user defined `.def` files and the automatically generated ones are already deleted by R.

FWIW the extensions used for this were originally from [`devtools::clean_dll()`](https://github.com/hadley/devtools/blob/b6a23be508043fd0ffc24316034b5e45bfc1a941/R/compile-dll.r#L54), probably `.def` should be removed there as well.

**Comment by jimhester** [comment]
Thanks!

**Comment by jeroenooms** [comment]
@jimhester yes it should be removed form devtools as well. Can you easily fix that or should i make a pr?

**Comment by jimhester** [comment]
I would make a PR just in case there is a use case we haven't thought of so winston/hadley can see it.

**Pull request merged**
